name: License checker

on:
  workflow_call: {}

permissions: read-all

jobs:
  check-license:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
          config: .github/.licenserc.yaml
