name: License checker

on:
  workflow_call: {}

permissions: read-all

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Check License Header
        uses: apache/skywalking-eyes@438e4ea5682269933ea2c8b5608662e52af26959 # v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
          config: .github/.licenserc.yaml
